### ISSUE TITLE
Allow absolute paths

### ISSUE THREAD

**Issue by RickZaki** [brielov/express-load-routes#1]
It would be nice to also support absolute paths to routes.  I like to put all my server side code into a subdirectory in the project.  Now I have to add the subdirectory to the load:
require('express-load-routes')(app, 'server/routes');
It would be nice to make things more relative and be able to simply use something like:
require('express-load-routes')(app, __dirname + '/routes');

**Comment by tujamaica** [comment]
I'm sorry for the delay, I think you are right. Let me see what I can do.

**Comment by brielov** [comment]
I've replaced this repository with brielov/expresso-router which is part of brielov/expresso (an express api boilerplate). It uses absolute paths instead. You can check it out and let me know what you think. Cheers

**Comment by brielov** [comment]
@

**Comment by brielov** [comment]
@RickZaki I've replaced this repository with brielov/expresso-router which is part of brielov/expresso (an express api boilerplate). It uses absolute paths instead. You can check it out and let me know what you think. Cheers
